---
stages:
  - build

build_sql_boot:
  stage: build
  tags:
    - deploy-all-runner
  script:
    - mvn frontend:install-node-and-npm@install-node-and-npm
    - mvn frontend:npm@npm-install
    - mvn frontend:npm@npm-run-build
    - mvn antrun:run@copy
    - mvn package
    - mvn rpm:rpm
    - curl --fail -u $ARTIFACTORY_USERNAME:$ARTIFACTORY_PASSWORD -X PUT https://repo.croc.ru/artifactory/pstgrscroc.rpm-snapshots-local/sql-boot-0.5.1-1.noarch.rpm -T ./target/rpm/sql-boot/RPMS/noarch/sql-boot-0.5.1-1.noarch.rpm
  artifacts:
    paths:
    - target/sql-boot.zip
    expire_in: 1 day
