dist: trusty

language: java

jdk:
  - openjdk8

sudo: required

services:
  - docker

## Run integration tests
script:
  - mvn verify
  - mvn jacoco:report coveralls:report -Pcoverall
  - mvn docker:build

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push mgramin/sql-boot
