dist: trusty

language: java

jdk:
  - openjdk8

sudo: required

services:
  - docker

## Run integration tests
script:
  - mvn verify
  - mvn jacoco:report coveralls:report -Pcoverall
  - mvn docker:build

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push mgramin/sql-boot

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: target/sql-boot.zip
  skip_cleanup: true
  name: v0.2.0
  on:
    all_branches: true