dist: trusty

language: java

jdk:
  - openjdk8

sudo: required

services:
  - docker

## Run integration tests
script:
  - mvn frontend:install-node-and-npm@install-node-and-npm
  - mvn frontend:npm@npm-install
  - mvn frontend:npm@npm-run-build
  - mvn antrun:run@copy
  - mvn verify
  - mvn compile jacoco:report
  - mvn docker:build
  - mvn rpm:rpm

before_install:
  - sudo apt-get install -y rpm

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push mgramin/sql-boot

before_deploy:
  - export TRAVIS_TAG=v0.5.1
  - git tag $TRAVIS_TAG --force

deploy:
  provider: releases
  branch: master
  api_key: $GITHUB_TOKEN
  file:
    - target/sql-boot.zip
    - target/rpm/sql-boot/RPMS/noarch/sql-boot-0.5.1-1.noarch.rpm
  skip_cleanup: true
  name: v0.5.1
  overwrite: true
  on:
    tags: false
