version: '3'
services:

  db:
    image: sath89/oracle-xe-11g:latest
    ports:
      - "1521:1521"
    networks:
      mynetwork:
        aliases:
          - db_server
    hostname: db_server
  sql-boot:
    depends_on:
      - db
    links:
      - db
    environment:
      profile: oracle
      db_dev_user: system
      db_dev_password: oracle
      db_dev_url: jdbc:oracle.thin://db_server:1521/XE
