conf:
  connections:
    - name: h2
      baseFolder: file:conf/h2/database
      url: jdbc:h2:mem:;INIT=RUNSCRIPT FROM 'classpath:schema.sql';
      driverClassName: org.h2.Driver
      paginationQueryTemplate: >
        ${query} offset ${uri.pageSize()*(uri.pageNumber()-1)} limit ${uri.pageSize()}
      properties: >
        {
          "visible": false,
          "description": "Embedded db for unit tests only"
        }
    - name: dev
      baseFolder: file:conf/h2/database
      url: jdbc:h2:mem:;INIT=RUNSCRIPT FROM 'classpath:schema.sql';
      driverClassName: org.h2.Driver
      paginationQueryTemplate: >
        ${query} offset ${uri.pageSize()*(uri.pageNumber()-1)} limit ${uri.pageSize()}
      properties: >
        {
          "color": "green",
          "description": "Develop demo db",
          "css_class": "fas fa-fw fa-2x fa-tools"
        }
    - name: test
      baseFolder: file:conf/h2/database
      url: jdbc:h2:mem:;INIT=RUNSCRIPT FROM 'classpath:schema.sql';
      driverClassName: org.h2.Driver
      paginationQueryTemplate: >
        ${query} offset ${uri.pageSize()*(uri.pageNumber()-1)} limit ${uri.pageSize()}
      properties: >
        {
          "color": "orange",
          "description": "Testing demo db",
          "css_class": "fas fa-fw fa-2x fa-bug"
        }
    - name: prod
      baseFolder: file:conf/h2/database
      url: jdbc:h2:mem:;INIT=RUNSCRIPT FROM 'classpath:schema.sql';
      driverClassName: org.h2.Driver
      paginationQueryTemplate: >
        ${query} offset ${uri.pageSize()*(uri.pageNumber()-1)} limit ${uri.pageSize()}
      properties: >
        {
          "color": "red",
          "description": "Production demo db",
          "css_class": "fas fa-fw fa-2x fa-bicycle"
        }


server:
  port: 8007
