conf:
  connections:
    - name: h2
      baseFolder: file:conf/common/database
      url: jdbc:h2:mem:;INIT=RUNSCRIPT FROM 'classpath:schema.sql';
      driverClassName: org.h2.Driver
    - name: oracle_jdbc
#      baseFolder: file:conf/sql-boot-oracle/database
      baseFolder: file:conf/common/database
      url: jdbc:oracle:thin:@localhost:1521:XE
      driverClassName: oracle.jdbc.OracleDriver
      user: system
      password: oracle
    - name: oracle
      baseFolder: file:conf/sql-boot-oracle/database
#      baseFolder: file:conf/common/database
      url: jdbc:oracle:thin:@localhost:1521:XE
      driverClassName: oracle.jdbc.OracleDriver
      user: system
      password: oracle
    - name: postgres
#      baseFolder: file:conf/common/database
      baseFolder: file:conf/sql-boot-postgresql/database
      url: jdbc:postgresql://localhost:54321/demo
      driverClassName: org.postgresql.Driver
      user: postgres
      password: postgres
    - name: clickhouse
      baseFolder: file:conf/common/database
      url: jdbc:clickhouse://localhost:8123/default
      driverClassName: ru.yandex.clickhouse.ClickHouseDriver
    - name: cassandra
      baseFolder: file:conf/common/database
      url: jdbc:c*://localhost:9042/system
      driverClassName: com.github.cassandra.jdbc.CassandraDriver

server:
  port: 8008

spring:
  security:
    enabled: false
management:
  security:
    enabled: false
security:
  basic:
    enabled: false



