conf:

  dialects:
    - name: h2
      paginationQueryTemplate: >
        {{ query }} limit {{ uri.pageSize() }} offset {{ uri.pageSize()*(uri.pageNumber()-1) }}

  endpoints:
    - name: h2
      host: 127.0.0.1
      confDir: conf/h2/md/database
      properties:
          sql_dialect: h2
          jdbc_url: jdbc:h2:mem:;INIT=RUNSCRIPT FROM 'classpath:schema.sql';
          jdbc_driver_class_name: org.h2.Driver
          jdbc_user:
          jdbc_password:
          visible: true
          description: Embedded db for unit tests only

server:
  port: 8007

#Metrics related configurations
management.endpoint.metrics.enabled: true
management.trace.http.enabled: true
management.auditevents.enabled: true


management:
  endpoints:
    web:
      exposure:
        include: "httptrace"
  metrics:
    export:
      statsd:
        enabled: true
        flavor: 'telegraf'
        port: 8125
  trace:
    http:
      include: RESPONSE_HEADERS