tables: |
  select t.owner as "schema"
       , t.table_name as "table"
    from all_tables t
   where lower(t.owner) like '$schema'
     and lower(t.table_name) like '$table'

table.sql.create: |
  select DBMS_METADATA.GET_DDL('TABLE', '$table.name', '$schema') as ddl from dual

table.sql.drop: |
  drop table "$schema"."$table.name";