conf:

  dialects:
    - name: h2
      paginationQueryTemplate: >
        ${query} offset ${uri.pageSize()*(uri.pageNumber()-1)} limit ${uri.pageSize()}
    - name: postgres
      paginationQueryTemplate: >
        ${query} offset ${uri.pageSize()*(uri.pageNumber()-1)} limit ${uri.pageSize()}
    - name: osquery
      paginationQueryTemplate: >
        ${query} limit ${uri.pageSize()*(uri.pageNumber()-1)}, ${uri.pageSize()}

  endpoints:
    - name: h2
      host: 127.0.0.1
      properties: >
        {
          "sql.dialect": "h2",
          "fs.base.folder": "conf/h2/md/database",
          "jdbc.url": "jdbc:h2:mem:;INIT=RUNSCRIPT FROM 'classpath:schema.sql';",
          "jdbc.driver.class.name": "org.h2.Driver",
          "jdbc.user": "",
          "jdbc.password": "",
          "os.query.rest.port": "8082",
          "visible": false,
          "description": "Embedded db for unit tests only"
        }

server:
  port: 8007

#Metrics related configurations
management.endpoint.metrics.enabled: true
management.endpoints.web.exposure.include: '*'
management.endpoint.prometheus.enabled: true
management.metrics.export.prometheus.enabled: true