conf:
  connections:
    - name: h2
      baseFolder: file:conf/h2/database
      url: jdbc:h2:mem:;INIT=RUNSCRIPT FROM 'classpath:schema.sql';
      driverClassName: org.h2.Driver


server:
  port: 8007

spring:
  security:
    enabled: false
management:
  security:
    enabled: false
security:
  basic:
    enabled: false



