conf:

  dialects:
    - name: h2
      paginationQueryTemplate: >
        ${query} offset ${uri.pageSize()*(uri.pageNumber()-1)} limit ${uri.pageSize()}
    - name: postgres
      paginationQueryTemplate: >
        ${query}

  connections:
    - name: h2
      dialect: h2
      baseFolder: file:conf/h2/md/database
      url: jdbc:h2:mem:;INIT=RUNSCRIPT FROM 'classpath:schema.sql';
      driverClassName: org.h2.Driver
      properties: >
        {
          "visible": false,
          "description": "Embedded db for unit tests only"
        }
    - name: dev
      dialect: h2
      baseFolder: file:conf/h2/md/database
      url: jdbc:h2:mem:;INIT=RUNSCRIPT FROM 'classpath:schema.sql';
      driverClassName: org.h2.Driver
      properties: >
        {
          "color": "green",
          "description": "Develop demo db",
          "css_class": "fas fa-fw fa-2x fa-tools"
        }
    - name: test
      dialect: h2
      baseFolder: file:conf/h2/md/database
      url: jdbc:h2:mem:;INIT=RUNSCRIPT FROM 'classpath:schema.sql';
      driverClassName: org.h2.Driver
      properties: >
        {
          "color": "orange",
          "description": "Testing demo db",
          "css_class": "fas fa-fw fa-2x fa-bug"
        }
    - name: prod
      dialect: h2
      baseFolder: file:conf/h2/md/database
      url: jdbc:h2:mem:;INIT=RUNSCRIPT FROM 'classpath:schema.sql';
      driverClassName: org.h2.Driver
      properties: >
        {
          "sql.dialect": "postgres",
          "fs.base.folder": "conf/sql-config/database",
          "jdbc.url": "jdbc:postgresql://81.23.10.106:5432/postgres",
          "jdbc.driver.class.name": "org.postgresql.Driver",
          "jdbc.user": "postgres",
          "jdbc.password": "postgres",
          "os.query.rest.port": "8082",
          "visible": false,
          "description": "Embedded db for unit tests only"
        }

server:
  port: 8007

#Metrics related configurations
management.endpoint.metrics.enabled: true
management.endpoints.web.exposure.include: '*'
management.endpoint.prometheus.enabled: true
management.metrics.export.prometheus.enabled: true