conf:
  connections:
    - name: h2
      baseFolder: file:conf/h2/database
      url: jdbc:h2:mem:;INIT=RUNSCRIPT FROM 'classpath:schema.sql';
      driverClassName: org.h2.Driver
    - name: common
      baseFolder: file:conf/common/database
      url: jdbc:h2:mem:;INIT=RUNSCRIPT FROM 'classpath:schema.sql';
      driverClassName: org.h2.Driver
    - name: oracle
      baseFolder: file:conf/sql-boot-oracle/database
      url: jdbc:oracle:thin:@192.168.0.101:1521:XE
      driverClassName: oracle.jdbc.OracleDriver
      user: system
      password: oracle
    - name: postgres
      baseFolder: file:conf/sql-boot-postgresql/database
      url: jdbc:postgresql://192.168.0.101:5432/demo
      user: postgres
      password: postgres

server:
     port: 8007